### ISSUE TITLE
Add support for insights feature

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#1142]
**What would you like to be added**:
With accumulated deployment data, we can provide the graphs that help users to understand the delivery performance of a single application or the whole project. 

According to DORA’s [The Accelerate State of DevOps Report](https://services.google.com/fh/files/misc/state-of-devops-2019.pdf), we plan to provide the following metrics:
- [ ] Lead Time for Changes: How long does it take to go from code committed to code successfully running on production.
- [x] Deployment Frequency: How often does your application/project deploy code to production.
- [ ] Mean Time To Restore: How long does it generally take to restore service when a service incident occurs.
- [x] Change Failure Rate: How often deployment failures occur in production that requires an immediate remedy (fix, rollback…).

Harness's Continuous Insights shows nearly ideal graphs:
![image](https://user-images.githubusercontent.com/19730728/100295807-f3cc8480-2fcd-11eb-9562-bc5ec1435dc0.png)

### Links:
- https://harness.io/continuous-delivery-bak/continuous-insights
- https://harness.io/2019/10/continuous-insights-accelerate-devops-metrics/

### TODO:
- [x] Step0: Submit an RFC like: https://github.com/pipe-cd/pipe/pull/1114
- [x] Step1: Collect data every time web requests 
- [x] Step2: Redesign the pipecd-ops to collect data periodically
