### ISSUE TITLE
Implement admin authentication by username and password

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#259]
#412 

# Todo
- [ ] Password authentication handler
- [ ] Load Secret key to sign jwt token
- [ ] Enable password authentication
