### ISSUE TITLE
Implement API for web frontend

### ISSUE THREAD

**Issue by cakecatz** [pipe-cd/pipecd#406]
**What would you like to be added**:
A central issue for web-api to meet the requirement of v1.alpha.

### Piped

- [x] enabling https://github.com/pipe-cd/pipe/pull/423
- [x] recreate key(disabling and regenerate) https://github.com/pipe-cd/pipe/issues/415

### Deployment Detail

- [x] commit link https://github.com/pipe-cd/pipe/issues/414
- [ ] PR Link https://github.com/pipe-cd/pipe/issues/606

### Application

- [x] Enable https://github.com/pipe-cd/pipe/pull/422
- [x] Deployment Config Templates https://github.com/pipe-cd/pipe/issues/467
- [ ] Add piped to filter option https://github.com/pipe-cd/pipe/issues/575

### Web Authentication/Authorization

- [ ] login https://github.com/pipe-cd/pipe/issues/412
- [ ] logout

**Why is this needed**:
