### ISSUE TITLE
Livestate feature in plugin architecture

### ISSUE THREAD

**Issue by ffjlabo** [pipe-cd/pipecd#5363]
**What would you like to be added**:

This issue is the meta (epic) issue for the livestate feature in plugin architecture.

TODO
- [x] make RFC
- [x] define an interface for livestate
- [ ] ~implement livestate store on the plugin side~
- [x] implement livestate reporter on the piped side
- [x] Implement Web UI

**Why is this needed**:

**Comment by ffjlabo** [comment]
completed
