### ISSUE TITLE
[epic][plugin] Implement Stage Plugins

### ISSUE THREAD

**Issue by t-kikuc** [pipe-cd/pipecd#5367]
**What would you like to be added**:

Support the following stages in the plugin architecture.

- [x] `WAIT` Stage
    - [x] Init server #5445
    - [x] Use metadata store #5520
    - [x] Core logic of waiting (without handling the stopSignal)
    - [x] Optimize stage config location
    - [x] Planner methods #5504
- [x] `WAIT_APPROVAL` Stage #6067
- [x] `ANALYSIS` Stage #6068
- [x] `SCRIPT_RUN` Stage #5901

Crossing-tasks: 
- [x] Piped) Define and handle `skipOn` options
- [x] Piped&Plugin) Add Notifier methods (WaitApproval)
- [x] Handling Skip and Approve actions on UI
    - [x] API) Define `ListCommands()` and `ManualOperation`
    - [x] SDK) Wrap the `ListCommands()`
    - [x] Piped(commandStore) 
         - [x] backend of `ListCommands()`
         - [x] report stages after finishing
    - [x] UI) Show the skip button if the stage is skippable (Make compatible with pipedv0)
    - [x] UI) Show the approval button if the stage is approvable (Make compatible with pipedv0)
        - [x] How to restrict approvals from only specified users
    - [x] Add to the SDK

Need Design in advance
- [x] Analysis > Analysis Template #6036 
- [x] Analysis > analysisResultStore

~Note: We've not determined how to support the `SCRIPT_RUN` Stage in the plugin architecture.~

**Why is this needed**:

Stages will also become plugins, not built-in code.
That will extend the flexibility of pipelines.

**Comment by t-kikuc** [comment]
> [ ] Piped&Plugin) Handle commands of skipStage and approveStage (Analysis, WaitApproval)
> [ ] UI&model) Add skippable flag to PipelineStage and switch by it on UI (Analysis)
> [ ] UI&model) Add approvable flag to PipelineStage and switch by it on UI (WaitApproval)

The overview of handling SkipStage and ApproveStage will be like this:

![Image](https://github.com/user-attachments/assets/2d7df502-4609-4e0c-b750-05ae8f59b446)




- Add `skippable` and `approvable` flags in the model `PipelineStage`.
- Set them true in `BuildPipelineSyncStages()` of Analysis and WaitApproval stage plugins.
- Define and use `ListStageCommands()` and `ReportStageCommandHandled()` APIs from a plugin to Piped to handle commands on the plugin side.
- On UI, show the Skip button if the stage is `skippable`, and show the Approve dialog if the stage is `approvable`



This architecture enables other plugins to use SkipStage and ApproveStage.

**Comment by t-kikuc** [comment]
New overview of the command handling:

![Image](https://github.com/user-attachments/assets/90205b5c-4ab7-48ab-a0a4-63ebdbcab45c)

**Comment by t-kikuc** [comment]
Finally we prepared everything we need to implement ANalysis/WaitApproval plugins.  

Let's move on to implementing these plugins!

**Comment by t-kikuc** [comment]
completed
